server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    lazy-initialization: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
#  data:
#    mongodb:
#      uri: mongodb://admin:pass@localhost/auth?authSource=admin
############################################
#         Mongo db configuration           #
############################################
  data:
    mongodb:
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:localhost}
      database: ${MONGODB_DATABASE:otd_qlf_dev_image_processor}
############################################
#           Log configuration              #
############################################
logging:
  level:
    io:
      netty: ${NETTY_LOG_LEVEL:INFO}
    reactor: ${REACTOR_LOG_LEVEL:INFO}